name: version

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  build:
    environment: version
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        architecture: x64
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USER }}
        server-password: ${{ secrets.OSSRH_PASSWORD }}
        gpg-passphrase:  ${{ secrets.OSSRH_PASSWD }}
        gpg-private-key: ${{ secrets.OSSRH_KEY }}
    - run: mvn -B package -Dgpg.skip
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_PASSWD }}
