name: Dream Begins

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        architecture: x64
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USER }}
        server-password: ${{ secrets.OSSRH_PASSWORD }}
        gpg-passphrase:  ${{ secrets.OSSRH_PASSWD }}
        gpg-private-key: ${{ secrets.OSSRH_KEY }}
    - uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - run: mvn -B -U verify
